### ISSUE TITLE
Incomplete optiboot_x build for mega0 and ATtiny0/1/2 AVRs

### ISSUE THREAD

**Issue by mcuee** [Optiboot/optiboot#364]
The following is not complete, missing many chips.
https://github.com/Optiboot/optiboot/blob/master/optiboot/bootloaders/optiboot/makeall.mega0.sh

**Comment by mcuee** [comment]
Reference:
https://github.com/MCUdude/MegaCoreX (all chips will support optiboot_x)
https://github.com/SpenceKonde/megaTinyCore (most of the chip will support optiboot_x)

**Comment by WestfW** [comment]
But many of those chips will wind up with identical code paths and binarie, since (for example) tiny0/tiny1/tiny2 are identical wrt the bootloader, and flash size is no longer relevant.  The makeall.mega0 script should be testing at least one rom each relevant part of the tree.

im leaving it up to Spence and mcudude to build the exhaustive list of .hex files, if they desire.
(Or that’s the theory anyway.  I could be convinced that I’ve left out important examples.)

**Comment by mcuee** [comment]
> But many of those chips will wind up with identical code paths and binarie, since (for example) tiny0/tiny1/tiny2 are identical wrt the bootloader, and flash size is no longer relevant. The makeall.mega0 script should be testing at least one rom each relevant part of the tree.

That is indeed true.
Reference: https://github.com/SpenceKonde/megaTinyCore/tree/master/megaavr/bootloaders/hex

> im leaving it up to Spence and mcudude to build the exhaustive list of .hex files, if they desire.
> (Or that’s the theory anyway. I could be convinced that I’ve left out important examples.)

Fair enough.

**Comment by mcuee** [comment]
In that case, I will close this issue for now.
