### ISSUE TITLE
EEPROM r/w support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Optiboot/optiboot#94]
```
Here is two diffs for enable EEPROM support.

 - Fixes bug from Issue #65
 - Adds extra EEPROM page r/w code
 - Still complied to 256 words if LED_START_FLASHES=0 and LED_DATA_FLASH=0
 - Tested on Freeduino with atmega328p
```

Original issue reported on code.google.com by `av1024@gmail.com` on 1 Jan 2014 at 2:29

Attachments:
- [optiboot.c.diff](https://storage.googleapis.com/google-code-attachments/optiboot/issue-94/comment-0/optiboot.c.diff)
- [makefile.diff](https://storage.googleapis.com/google-code-attachments/optiboot/issue-94/comment-0/makefile.diff)

**Comment by jj1bdx** [comment]
EEPROM read/write address is word-aligned and not byte aligned. I've found this bug on ATmega328P with BIGBOOT enabled. This is due to multiplying the address by two at https://github.com/Optiboot/optiboot/blob/master/optiboot/bootloaders/optiboot/optiboot.c#L565 - is there any way to fix this? (I think some more code is allowed)

**Comment by WestfW** [comment]
Created https://github.com/Optiboot/optiboot/issues/179

**Comment by WestfW** [comment]
Fixed, I think. https://github.com/Optiboot/optiboot/commit/a50f47b8acf28ea51e72c08914d8811563dcb869
Note avrdude bug: https://savannah.nongnu.org/bugs/?48131
